apiVersion: v2
appVersion: v0.1.0
description: A network load-balancer implementation for Kubernetes using standard
  routing protocols
home: https://metallb.universe.tf
icon: https://metallb.universe.tf/images/logo/metallb-white.png
name: metallb
type: application
version: 0.1.0
